### PR TITLE
Fix confirm_cards: we had an issue where many cards that we're supposed to show to the opponent were not displayed as they should've been.

### PR DESCRIPTION
**Pull request by thyhellcat**

### CODE REVIEW

**Comment by Timtam** [comment]
Before merging any kind of fix, I want to know what the actual problem was you're trying to fix here. Mind opening an issue for that one first before providing a solution for it?
I'm unable to review PRs without knowing what I have to do :D.

**Comment by thyhellcat** [comment]
An example of wrong behaviour we had before this:

We assume it's a duel between Kriss and Tsp
* kriss activates terraforming
* kriss adds whatever fieldspell to hand
// Kriss sees:
  Tsp shows you one card: 1: whatever fieldspell
// Tsp sees:
  Kriss card o28 returned to their hand.

After fixing:
// Kriss sees:
  Card o28 whatever fieldspell returned to hand.
// Tsp sees:
  Kriss shows you one card: 1: whatever fieldspell

**Comment by Timtam** [comment]
Thanks, but AFAIK this problem didn't occurred before. Unless TSP updated the core and the YGOPRO Core changed some handlers, only your last PR could be the culprit here. I wasn't able to properly review the last one before @tspivey merged it, but looking at it already seemed a bit unstable. Maybe its time to go back, revert the previous PR from you and invent a better, more stable approach to fix the underlying problem instead of trying to use duct tape over and over again, hoping that it might solve the problem some day.
Or am I wrong here? When I used to play on the MUD like 1 month ago, the messages showed like expected and not as messed up as you described.

**Comment by thyhellcat** [comment]
This has been causing issues for months. And yes, it is due to ygopro-core's behaviour. Previous fix was quite bad, but Tsp and I didn't find a better solution by then. After that we realised we had access to card.controller. Don't ask me why, but nowadays ygopro-core sometimes sends weird players handles, and it really depends on where the cards come from / go to. Previous PR was actually fine far as we knew, it's just that we realised that in some instances the player handle we were getting was still wrong, depending on whether one was going first or second. At least card.controller seems to be 100% reliable so far.

**Comment by Timtam** [comment]
@tspivey do you know how stable this PR is (are we running this on the server right now)? Merge or not? Its pretty outdated and i'm not sure how relevant it still is

**Comment by Timtam** [comment]
already fixed by @tspivey

**Pull request closed without merging**
