### PR TITLE
Added soundpack command (used by the new soundpack)

### PR DESCRIPTION
**Pull request by JessicaTegner**
This pr adds a soundpack command.

Right now this only contains version (so soundpack version abc) but can be expanded later if we want.

This goes with the new mush soundpack that calls soundpack version on login to check for updates.
It's the server that tells the player if their soundpack is out of date.

### CODE REVIEW

**Comment by Timtam** [comment]
Just as a side note, I don't like a soundpack command here. That feels like we're mixing up two independent projects. You'd always need to push and restart (!) the server for a soundpack update announcement, that doesn't feel right in the slightest. You can achieve the same by checking values on the GitHub repository of the soundpack if that is what you want.
BTW, what is it all about with the new soundpack, why not continue to maintain the one that already exists, its public over all: https://github.com/Timtam/yugioh-soundpack/

**Comment by JessicaTegner** [comment]
yep good point as @tspivey  also said. Also figured that the soundpack wasn't being updated anymore and haven't heard of anyone seeing you around

**Comment by JessicaTegner** [comment]
I would have nothing against sending prs over. The same argument I had for TSP I'll tell you. I'm trying to streamline and automate as many things about the mud as possible , since the current devs (you and tsp) aren't really around (and in tsps case, doesn't really like the game).

I'm simply trying to make everyones life easier

**Comment by tspivey** [comment]
Once we get a soundpack updater in place, #272 should be as easy as a merge into both soundpack and game, then ask players to update.

**Comment by JessicaTegner** [comment]
the issue with that would be that you can't override files while they are in use. That's why it's splitted up into a separate process

**Comment by Timtam** [comment]
Yeah, thats not the issue that troubles me here. You already got a bat in place which downloads and replaces the soundpack don't you? That can just stay as it is, I just don't like the soundpack version check and download on the server side.

**Pull request closed without merging**
