### PR TITLE
Hand-made banlist: 2019.1 TCG. Does NOT include up-to-date OCG list.

### PR DESCRIPTION
**Pull request by thyhellcat**

### CODE REVIEW

**Comment by Timtam** [comment]
Shouldn't we wait for e.g. percy releasing the entire banlist, including ocg, just to make sure here? @tspivey any comments?

**Comment by tspivey** [comment]
I'm holding off on this one for now. We've been running with the handmade one which works well, but ygopro has a new lflist.conf with TCG and OCG in it, so I think I can use that. Also, I'm not sure when the next one comes out, but probably soon now.

**Comment by thyhellcat** [comment]
Like Tyler said, we’ve been running this for 2+ months and it’s fine. I first built it cause the ygopro lads took ages to update the banlist when it came out back in January. We can always come back to using theirs if they update it properly. The next one is supposed to be released in the upcoming days. When it drops I can immediately build it, and we can use ygopro’s if they make it including OCG. TBF no one plays with the OCG ones anyway but yeah.

**Comment by Timtam** [comment]
No longer required :)

**Pull request closed without merging**
