### PR TITLE
Added 60 cards limit to decks to follow official YGO rulling.

### PR DESCRIPTION
**Pull request by thyhellcat**

### CODE REVIEW

**Comment by Timtam** [comment]
I however don't like the idea of forcing the players to stick to that rule. We aren't a tournament platform, we do have newbies as well, and newbies should be free to do what they want in certain limits. We got the card limit of 120 earlier, and even that one was random. As soon as newbies become more experienced, they will stick to either 40 or 60 cards anyway, but not allowing more than 60 doesn't sound quite nice to me.
I also want to prevent just adding in all rules which can be found on tournaments as well, just as time outs. We are here for training and testing, not just tournament duelling.
@tspivey what about you?

**Comment by tspivey** [comment]
I merged it for now, but I can always back it out. One reason is that apparently the game will crash if you have too many cards in a deck. I thought it was 255, but there might be a signed int somewhere in there so 127, and the default was 200.

**Comment by Timtam** [comment]
Yeah I knew there was a technical limit by YGOPRO here, but I didn't know that one when reworking the deck editor. We can limit it to 120 though, but 60 looks much to strict to me.
I however am happy with a democratic decision here, if you don't think that 60 cards are inappropriate, we can of course leave it how it is now. What do the people in-game say about this?

**Comment by thyhellcat** [comment]
Hi there,

Sorry for the late response but we’re in quite different time zones. 
The reason why I wanted to add this is that allowing more than 60 cards does not help newbies getting better at the game. I’m not into tournament-based only stuff and hardcore high level. It’d be cool to have a full tournament mode with time and FT2 / 3 games, cause we sometime think of organising competitions. But that would also require the creation of side decks and stuff, which would take quite a bit of time to develop.
I do believe that adding this will just force players to think a bit more when creating their decks, it’s not too restrictive. As you said, we’re here to have fun; IMO no one will really complain about this limitation. Also, all high level players do think it’s a positive evolution, as far as I know. 

Anyway, we can introduce it and see what it gives. We can always remove that commit from master or improve it (e.g. create a set of rules that follow MR4 and give players the possibility to activate it or not).

Kriss

**Pull request merged**
